version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    assignees:
      - ssshhhooota
    commit-message:
      prefix: ci
      include: scope
    cooldown:
      default-days: 5
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go
    assignees:
      - ssshhhooota
    commit-message:
      prefix: build
      include: scope
    cooldown:
      default-days: 5
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      go-minor-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
